import "./globals.css";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import ReduxProvider from "@/providers/ReduxProvider";
import TopNav from "@/components/TopNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ReduxProvider>
        <TopNav />
        <body className={inter.className}>{children}</body>
      </ReduxProvider>
    </html>
  );
}
